'use client';

import { useEffect, useMemo, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000';
type Applicant = {applicant_id:string; applicant_name:string; annual_income:number; loan_amount:number; debt_to_income:number; credit_utilization:number; late_payments_12m:number; default_probability:number; risk_band:string; loan_purpose:string; employment_type:string};
type Overview = {portfolio:{applications:number;high_risk:number;critical:number;avg_default_probability:number;observed_default_rate:number};model:{name:string;roc_auc:number;accuracy:number;precision:number;recall:number;f1:number};risk_distribution:{label:string;count:number}[];feature_importance:{feature:string;importance:number}[];comparison:{model:string;roc_auc:number;accuracy:number;precision:number;recall:number;f1:number}[]};

export default function Home(){
  const [overview,setOverview]=useState<Overview|null>(null);
  const [rows,setRows]=useState<Applicant[]>([]);
  const [query,setQuery]=useState(''); const [risk,setRisk]=useState('All'); const [selected,setSelected]=useState<Applicant|null>(null);
  const [form,setForm]=useState({age:35,annual_income:80000,loan_amount:180000,employment_years:6,credit_history_months:84,debt_to_income:.28,credit_utilization:.32,late_payments_12m:0,credit_inquiries_6m:1,savings_balance:25000,existing_debt:15000,dependents:1,monthly_expenses:3500,home_ownership:'Rent',loan_purpose:'Personal',employment_type:'Salaried'});
  const [score,setScore]=useState<any>(null); const [loading,setLoading]=useState(false);

  async function load(){ const [o,a]=await Promise.all([fetch(`${API}/api/overview`),fetch(`${API}/api/applicants?limit=40`)]); setOverview(await o.json()); setRows(await a.json()); }
  async function loadFiltered(){ const q=new URLSearchParams({limit:'40'}); if(query)q.set('search',query); if(risk!=='All')q.set('risk',risk); const r=await fetch(`${API}/api/applicants?${q}`); setRows(await r.json()); }
  useEffect(()=>{load().catch(console.error)},[]); useEffect(()=>{const t=setTimeout(()=>loadFiltered().catch(console.error),200); return()=>clearTimeout(t)},[query,risk]);
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true); try{const r=await fetch(`${API}/api/score`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setScore(await r.json())}finally{setLoading(false)}}
  const maxImp=useMemo(()=>Math.max(...(overview?.feature_importance.map(x=>x.importance)||[1])),[overview]);
  return <main className="page">
    <header className="top"><div className="brand"><div className="mark">C</div><div><div className="eyebrow">CREDIT RISK INTELLIGENCE</div><h1>CreditShield AI</h1></div></div><div className="live"><span></span> Model service online</div></header>
    <section className="hero"><div><p className="kicker">UNDERWRITING ANALYTICS</p><h2>Turn borrower data into defensible risk decisions.</h2><p className="lede">CreditShield combines classification, probability calibration, feature analysis and portfolio monitoring to help lending teams identify default risk earlier and explain the drivers behind each score.</p><div className="heroTags"><span>ML-driven</span><span>Explainable</span><span>API-ready</span></div></div><div className="heroStat"><div className="mini">CHAMPION MODEL</div><b>{overview?.model.name || 'Loading…'}</b><div className="big">{overview ? (overview.model.roc_auc*100).toFixed(1)+'%' : '—'}</div><div className="muted">ROC-AUC on held-out test data</div></div></section>
    <section className="kpis">{[['Applications',overview?.portfolio.applications.toLocaleString()||'—','portfolio'],['High risk',overview?.portfolio.high_risk.toLocaleString()||'—','requires review'],['Critical',overview?.portfolio.critical.toLocaleString()||'—','senior review'],['Avg risk',overview ? (overview.portfolio.avg_default_probability*100).toFixed(1)+'%':'—','estimated'],['F1 score',overview ? overview.model.f1.toFixed(3):'—','validation']].map((x,i)=><div className="kpi" key={i}><div className="label">{x[0]}</div><div className="num">{x[1]}</div><div className={i===2?'red':'muted'}>{x[2]}</div></div>)}</section>
    <section className="grid heroGrid"><div className="panel chartPanel"><div className="panelHead"><div><h3>Portfolio risk distribution</h3><p>Scored across the synthetic underwriting portfolio</p></div></div>{overview&&<div className="bars">{overview.risk_distribution.map(d=>{const pct=d.count/overview.portfolio.applications*100;return <div className="barRow" key={d.label}><div className="barLabel"><span>{d.label}</span><b>{d.count.toLocaleString()}</b></div><div className="track"><div className={`fill ${d.label.toLowerCase()}`} style={{width:`${Math.max(pct,3)}%`}}/></div><small>{pct.toFixed(1)}%</small></div>})}</div>}</div><div className="panel"><div className="panelHead"><div><h3>Model lab</h3><p>Independent test-set comparison</p></div></div>{overview?.comparison.map(m=><div className="modelRow" key={m.model}><div><b>{m.model}</b><span>ROC-AUC {m.roc_auc.toFixed(3)}</span></div><div className="metric">F1 {m.f1.toFixed(3)}</div></div>)}</div></section>
    <section className="grid main"><div className="panel tablePanel"><div className="panelHead"><div><h3>Priority applicant queue</h3><p>Highest estimated default probability first</p></div><div className="filters"><input placeholder="Search ID or name…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={risk} onChange={e=>setRisk(e.target.value)}><option>All</option><option>Low</option><option>Moderate</option><option>High</option><option>Critical</option></select></div></div><div className="table"><div className="tr head"><span>Applicant</span><span>Loan</span><span>DTI</span><span>Risk</span><span>Probability</span></div>{rows.map(r=><button className="tr" key={r.applicant_id} onClick={()=>setSelected(r)}><span><b>{r.applicant_id}</b><small>{r.applicant_name}</small></span><span>${Math.round(r.loan_amount).toLocaleString()}</span><span>{(r.debt_to_income*100).toFixed(0)}%</span><span><i className={`pill ${r.risk_band.toLowerCase()}`}>{r.risk_band}</i></span><span><b>{(r.default_probability*100).toFixed(1)}%</b></span></button>)}</div></div>
    <div className="panel"><div className="panelHead"><div><h3>Top risk drivers</h3><p>Model feature influence</p></div></div>{overview?.feature_importance.map(f=><div className="imp" key={f.feature}><div><span>{f.feature}</span><b>{f.importance.toFixed(2)}</b></div><div className="impTrack"><div style={{width:`${Math.min(100,f.importance/maxImp*100)}%`}}/></div></div>)}</div></section>
    <section className="panel scorer"><div className="panelHead"><div><h3>Live underwriting scorer</h3><p>Submit a hypothetical application and inspect model drivers.</p></div>{score&&<div className={`decision ${score.risk_band.toLowerCase()}`}>{score.risk_band} risk</div>}</div><form onSubmit={submit}><div className="formGrid">{[['age','Age'],['annual_income','Annual income'],['loan_amount','Loan amount'],['employment_years','Employment years'],['credit_history_months','Credit history (months)'],['debt_to_income','Debt-to-income'],['credit_utilization','Credit utilization'],['late_payments_12m','Late payments (12m)'],['credit_inquiries_6m','Credit inquiries (6m)'],['savings_balance','Savings balance'],['existing_debt','Existing debt'],['dependents','Dependents'],['monthly_expenses','Monthly expenses']].map(([k,l])=><label key={k}>{l}<input type="number" step="any" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}<label>Home ownership<select value={form.home_ownership} onChange={e=>setForm({...form,home_ownership:e.target.value})}>{['Own','Mortgage','Rent'].map(x=><option key={x}>{x}</option>)}</select></label><label>Loan purpose<select value={form.loan_purpose} onChange={e=>setForm({...form,loan_purpose:e.target.value})}>{['Home','Auto','Education','Business','Personal'].map(x=><option key={x}>{x}</option>)}</select></label><label>Employment type<select value={form.employment_type} onChange={e=>setForm({...form,employment_type:e.target.value})}>{['Salaried','Self-employed','Contract','Hourly'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="scoreBtn" disabled={loading}>{loading?'Scoring…':'Score application'}</button></form>{score&&<div className="scoreResult"><div className="scoreCard"><div className="mini">ESTIMATED DEFAULT PROBABILITY</div><div className="scoreNum">{(score.default_probability*100).toFixed(1)}%</div><p>{score.decision}</p></div><div className="driverCard"><div className="mini">TOP DRIVERS</div>{score.drivers.map((d:any)=><div className="driver" key={d.feature}><b>{d.feature}</b><span className={d.direction==='increases risk'?'red':'green'}>{d.direction}</span></div>)}</div></div>}</section>
    <footer>CreditShield AI · Synthetic demo data · Model outputs are decision-support signals, not lending decisions.</footer>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">APPLICANT DETAIL</div><h2>{selected.applicant_id}</h2><p className="muted">{selected.applicant_name}</p><div className={`riskHero ${selected.risk_band.toLowerCase()}`}><span>{selected.risk_band} risk</span><b>{(selected.default_probability*100).toFixed(1)}%</b><small>estimated default probability</small></div><div className="detailGrid">{[['Loan',`$${selected.loan_amount.toLocaleString()}`],['Income',`$${selected.annual_income.toLocaleString()}`],['DTI',`${(selected.debt_to_income*100).toFixed(0)}%`],['Utilization',`${(selected.credit_utilization*100).toFixed(0)}%`],['Late payments',selected.late_payments_12m],['Purpose',selected.loan_purpose]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><button className="scoreBtn" onClick={()=>{setForm(f=>({...f,annual_income:selected.annual_income,loan_amount:selected.loan_amount,debt_to_income:selected.debt_to_income,credit_utilization:selected.credit_utilization,late_payments_12m:selected.late_payments_12m}));setSelected(null);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}}>Use in scorer</button></div></div>}
  </main>
}
